/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibrariesIndexRouteImport } from './routes/libraries/index'
import { Route as LibrariesChar123LibnameChar125RouteImport } from './routes/libraries/{-$libname}'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesChar123LibnameChar125Route =
  LibrariesChar123LibnameChar125RouteImport.update({
    id: '/libraries/{-$libname}',
    path: '/libraries/{-$libname}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/libraries/{-$libname}': typeof LibrariesChar123LibnameChar125Route
  '/libraries': typeof LibrariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/libraries/{-$libname}': typeof LibrariesChar123LibnameChar125Route
  '/libraries': typeof LibrariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/libraries/{-$libname}': typeof LibrariesChar123LibnameChar125Route
  '/libraries/': typeof LibrariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/libraries/{-$libname}' | '/libraries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/libraries/{-$libname}' | '/libraries'
  id: '__root__' | '/' | '/about' | '/libraries/{-$libname}' | '/libraries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibrariesChar123LibnameChar125Route: typeof LibrariesChar123LibnameChar125Route
  LibrariesIndexRoute: typeof LibrariesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/{-$libname}': {
      id: '/libraries/{-$libname}'
      path: '/libraries/{-$libname}'
      fullPath: '/libraries/{-$libname}'
      preLoaderRoute: typeof LibrariesChar123LibnameChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibrariesChar123LibnameChar125Route: LibrariesChar123LibnameChar125Route,
  LibrariesIndexRoute: LibrariesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
