/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibrariesIndexRouteImport } from './routes/libraries/index'
import { Route as LibrariesChar123LibraryChar125RouteImport } from './routes/libraries/{-$library}'
import { Route as LibrariesChar123LibnameChar125IndexRouteImport } from './routes/libraries/{-$libname}/index'
import { Route as LibrariesChar123LibnameChar125MdChar123MarkdownChar125RouteImport } from './routes/libraries/{-$libname}/md/{-$markdown}'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesChar123LibraryChar125Route =
  LibrariesChar123LibraryChar125RouteImport.update({
    id: '/libraries/{-$library}',
    path: '/libraries/{-$library}',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibrariesChar123LibnameChar125IndexRoute =
  LibrariesChar123LibnameChar125IndexRouteImport.update({
    id: '/libraries/{-$libname}/',
    path: '/libraries/{-$libname}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route =
  LibrariesChar123LibnameChar125MdChar123MarkdownChar125RouteImport.update({
    id: '/libraries/{-$libname}/md/{-$markdown}',
    path: '/libraries/{-$libname}/md/{-$markdown}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/libraries/{-$library}': typeof LibrariesChar123LibraryChar125Route
  '/libraries': typeof LibrariesIndexRoute
  '/libraries/{-$libname}': typeof LibrariesChar123LibnameChar125IndexRoute
  '/libraries/{-$libname}/md/{-$markdown}': typeof LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/libraries/{-$library}': typeof LibrariesChar123LibraryChar125Route
  '/libraries': typeof LibrariesIndexRoute
  '/libraries/{-$libname}': typeof LibrariesChar123LibnameChar125IndexRoute
  '/libraries/{-$libname}/md/{-$markdown}': typeof LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/libraries/{-$library}': typeof LibrariesChar123LibraryChar125Route
  '/libraries/': typeof LibrariesIndexRoute
  '/libraries/{-$libname}/': typeof LibrariesChar123LibnameChar125IndexRoute
  '/libraries/{-$libname}/md/{-$markdown}': typeof LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/libraries/{-$library}'
    | '/libraries'
    | '/libraries/{-$libname}'
    | '/libraries/{-$libname}/md/{-$markdown}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/libraries/{-$library}'
    | '/libraries'
    | '/libraries/{-$libname}'
    | '/libraries/{-$libname}/md/{-$markdown}'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/libraries/{-$library}'
    | '/libraries/'
    | '/libraries/{-$libname}/'
    | '/libraries/{-$libname}/md/{-$markdown}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibrariesChar123LibraryChar125Route: typeof LibrariesChar123LibraryChar125Route
  LibrariesIndexRoute: typeof LibrariesIndexRoute
  LibrariesChar123LibnameChar125IndexRoute: typeof LibrariesChar123LibnameChar125IndexRoute
  LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route: typeof LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/{-$library}': {
      id: '/libraries/{-$library}'
      path: '/libraries/{-$library}'
      fullPath: '/libraries/{-$library}'
      preLoaderRoute: typeof LibrariesChar123LibraryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/{-$libname}/': {
      id: '/libraries/{-$libname}/'
      path: '/libraries/{-$libname}'
      fullPath: '/libraries/{-$libname}'
      preLoaderRoute: typeof LibrariesChar123LibnameChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/{-$libname}/md/{-$markdown}': {
      id: '/libraries/{-$libname}/md/{-$markdown}'
      path: '/libraries/{-$libname}/md/{-$markdown}'
      fullPath: '/libraries/{-$libname}/md/{-$markdown}'
      preLoaderRoute: typeof LibrariesChar123LibnameChar125MdChar123MarkdownChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibrariesChar123LibraryChar125Route: LibrariesChar123LibraryChar125Route,
  LibrariesIndexRoute: LibrariesIndexRoute,
  LibrariesChar123LibnameChar125IndexRoute:
    LibrariesChar123LibnameChar125IndexRoute,
  LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route:
    LibrariesChar123LibnameChar125MdChar123MarkdownChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
